/**
 * Multi-language translations for the application
 */

export const LANGUAGES = {
  en: { name: 'English', flag: '🇬🇧', nativeName: 'English' },
  nl: { name: 'Dutch', flag: '🇳🇱', nativeName: 'Nederlands' },
  es: { name: 'Spanish', flag: '🇪🇸', nativeName: 'Español' }
};

export const translations = {
  en: {
    // App
    appTitle: 'MDES XML Studio',
    selectModule: 'Select a Module',
    
    // Modules
    modules: {
      crs: 'CRS',
      fatca: 'FATCA',
      cbc: 'CBC'
    },
    moduleDescriptions: {
      crs: 'Common Reporting Standard',
      fatca: 'Foreign Account Tax Compliance Act',
      cbc: 'Country-by-Country Reporting'
    },
    
    // Navigation
    nav: {
      home: 'Home',
      generator: 'Generator',
      validator: 'Validator',
      correction: 'Correction',
      history: 'History',
      settings: 'Settings',
      help: 'Help'
    },
    
    // Actions
    actions: {
      generate: 'Generate',
      validate: 'Validate',
      save: 'Save',
      export: 'Export',
      import: 'Import',
      cancel: 'Cancel',
      confirm: 'Confirm',
      delete: 'Delete',
      edit: 'Edit',
      preview: 'Preview',
      download: 'Download',
      upload: 'Upload',
      browse: 'Browse',
      clear: 'Clear',
      reset: 'Reset',
      apply: 'Apply',
      close: 'Close',
      back: 'Back',
      next: 'Next',
      finish: 'Finish',
      generateCRS: 'Generate CRS XML File',
      generateFATCA: 'Generate FATCA XML',
      generateCBC: 'Generate CBC XML',
      generatingCRS: 'Generating CRS XML...',
      generatingFATCA: 'Generating FATCA XML...',
      generatingCBC: 'Generating CBC XML...',
      processing: 'Processing...',
      open: 'Open',
      downloadCSV: 'Download CSV'
    },
    
    // Form labels
    form: {
      sendingCountry: 'Sending Country',
      receivingCountry: 'Receiving Country',
      taxYear: 'Tax Year',
      reportingFI: 'Reporting Financial Institution',
      numFIs: 'Number of Financial Institutions',
      individualAccounts: 'Individual Accounts',
      organisationAccounts: 'Organisation Accounts',
      controllingPersons: 'Controlling Persons per Organisation',
      outputFile: 'Output File',
      inputFile: 'Input File',
      csvFile: 'CSV File',
      xmlFile: 'XML File',
      messageHeader: 'Message Header',
      fatcaMessageHeader: 'FATCA Message Header',
      cbcMessageHeader: 'CBC Message Header',
      sendingCompanyGIIN: 'Sending Company GIIN',
      sendingEntityTIN: 'Sending Entity TIN',
      transmittingCountry: 'Transmitting Country',
      reportingPeriod: 'Reporting Period (Year)',
      accountConfiguration: 'Account Configuration',
      substantialOwners: 'Substantial Owners per Org',
      filerCategory: 'Filer Category',
      testModeLabel: 'Test Mode',
      fatcaTestMode: 'Test Mode (FATCA11-14 indicators)',
      cbcTestMode: 'Test Mode (OECD11-13 indicators)',
      crsTestMode: 'Test Mode',
      reportingEntity: 'Reporting Entity (MNE)',
      cbcFileType: 'CBC File Type',
      domesticFiling: 'Domestic Filing',
      foreignExchange: 'Foreign Exchange',
      domesticFilingDesc: 'File submitted to your local tax authority. Receiving country will be the same as the transmitting country.',
      foreignExchangeDesc: 'File for automatic exchange with foreign tax authorities. You must specify the receiving country (partner jurisdiction).',
      mneGroupName: 'MNE Group Name',
      reportingEntityName: 'Reporting Entity Name',
      reportingRole: 'Reporting Role',
      cbcReportConfiguration: 'CBC Report Configuration',
      numJurisdictionReports: 'Number of Jurisdiction Reports',
      constEntitiesPerReport: 'Constituent Entities per Report',
      fileSize: 'File Size Configuration',
      dataSource: 'Data Source',
      randomData: 'Random Data',
      uploadCSV: 'Upload CSV',
      selectOutputLocation: 'Select output file location...',
      autoGenerated: 'Auto-generated if empty'
    },
    
    // Messages
    messages: {
      generating: 'Generating...',
      validating: 'Validating...',
      success: 'Success!',
      error: 'Error',
      warning: 'Warning',
      info: 'Information',
      fileGenerated: 'File generated successfully',
      validationPassed: 'Validation passed',
      validationFailed: 'Validation failed',
      noFileSelected: 'No file selected',
      invalidInput: 'Invalid input',
      requiredField: 'This field is required',
      confirmDelete: 'Are you sure you want to delete this?',
      unsavedChanges: 'You have unsaved changes'
    },
    
    // Settings
    settings: {
      title: 'Settings',
      theme: 'Theme',
      language: 'Language',
      autoSave: 'Auto-save',
      showTips: 'Show tips',
      recentFiles: 'Recent files',
      partnerJurisdictions: 'Partner Jurisdictions',
      keyboardShortcuts: 'Keyboard Shortcuts',
      appearance: 'Appearance',
      general: 'General'
    },
    
    // History
    history: {
      title: 'Generation History',
      noHistory: 'No generation history yet',
      clearHistory: 'Clear History',
      totalGenerated: 'Total Generated',
      totalAccounts: 'Total Accounts',
      lastGeneration: 'Last Generation'
    },
    
    // Recent files
    recentFiles: {
      title: 'Recent Files',
      noFiles: 'No recent files',
      clear: 'Clear recent files',
      open: 'Open',
      remove: 'Remove from list'
    },
    
    // Profiles
    profiles: {
      title: 'Saved Profiles',
      save: 'Save Profile',
      load: 'Load Profile',
      delete: 'Delete Profile',
      name: 'Profile Name',
      noProfiles: 'No saved profiles',
      saveSuccess: 'Profile saved successfully',
      loadSuccess: 'Profile loaded successfully'
    },
    
    // Validation
    validation: {
      title: 'Validation Results',
      valid: 'Valid',
      invalid: 'Invalid',
      errors: 'Errors',
      warnings: 'Warnings',
      details: 'Details'
    },
    
    // Batch
    batch: {
      title: 'Batch Processing',
      addFiles: 'Add Files',
      removeAll: 'Remove All',
      processAll: 'Process All',
      progress: 'Progress',
      completed: 'Completed',
      failed: 'Failed',
      pending: 'Pending',
      addFilesPrompt: 'Add files to generate in batch:',
      filesQueued: 'file(s) queued',
      clearAll: 'Clear All',
      crsFile: 'CRS File',
      fatcaFile: 'FATCA File',
      cbcFile: 'CBC File',
      outputLocation: 'Output Location',
      selectOutputFolder: 'Select output folder...',
      batchComplete: 'Batch Complete',
      succeeded: 'succeeded',
      ind: 'Ind',
      org: 'Org',
      reports: 'Reports'
    },
    
    // Diff
    diff: {
      title: 'XML Comparison',
      original: 'Original',
      modified: 'Modified',
      differences: 'Differences',
      noDifferences: 'No differences found',
      added: 'Added',
      removed: 'Removed',
      changed: 'Changed'
    },
    
    // Help
    help: {
      title: 'Help',
      shortcuts: 'Keyboard Shortcuts',
      documentation: 'Documentation',
      about: 'About'
    },

    // Dashboard
    dashboard: {
      title: 'Dashboard',
      welcome: 'Welcome',
      quickActions: 'Quick Actions',
      statistics: 'Statistics',
      recentActivity: 'Recent Activity'
    },

    // Templates
    templates: {
      title: 'Template Library',
      select: 'Select Template',
      apply: 'Apply Template',
      basicIndividual: 'Basic Individual Accounts',
      basicOrg: 'Basic Organisation Accounts',
      mixed: 'Mixed Account Types',
      correction: 'Correction File',
      largeDataset: 'Large Dataset'
    },

    // Common
    common: {
      loading: 'Loading...',
      saving: 'Saving...',
      processing: 'Processing...',
      done: 'Done',
      yes: 'Yes',
      no: 'No',
      ok: 'OK',
      or: 'or',
      and: 'and',
      all: 'All',
      none: 'None',
      select: 'Select',
      selected: 'Selected',
      search: 'Search',
      filter: 'Filter',
      sort: 'Sort',
      more: 'More',
      less: 'Less',
      show: 'Show',
      hide: 'Hide',
      expand: 'Expand',
      collapse: 'Collapse',
      refresh: 'Refresh',
      retry: 'Retry',
      copy: 'Copy',
      copied: 'Copied!',
      paste: 'Paste',
      cut: 'Cut',
      undo: 'Undo',
      redo: 'Redo',
      browse: 'Browse',
      output: 'Output',
      selectOutputLocation: 'Select output file location...',
      selectFolder: 'Select Folder',
      generating: 'Generating',
      testMode: 'Test Mode'
    },

    // Corrections
    corrections: {
      title: 'Corrections',
      generateCRS: 'Generate CRS702 Correction Files',
      generateFATCA: 'Generate FATCA Correction Files',
      generateCBC: 'Generate CBC Correction Files',
      sourceXmlFile: 'Source XML File',
      fromXmlFile: 'From XML File',
      fromCsvFile: 'From CSV File',
      selectXmlFile: 'Select XML file...',
      correctionType: 'Correction Type',
      generateCorrection: 'Generate Correction File',
      correctionCsvFile: 'Correction CSV File',
      requiredCsvFormat: 'Required CSV Format',
      viewCsvTemplate: 'View CSV Template',
      selectCorrectionCsv: 'Select correction CSV file...',
      correctionOptions: 'Correction Options',
      cbcCorrectionOptions: 'CBC Correction Options',
      correctionOECD2: 'Correction (OECD2)',
      deletionOECD3: 'Deletion (OECD3)',
      modifyExisting: 'Modify existing report data',
      deleteExisting: 'Delete existing report data',
      validFile: 'Valid File',
      validationFailed: 'Validation Failed'
    },

    // Tools
    tools: {
      title: 'Tools',
      countryCodeReplacer: 'Country Code Replacer',
      sourceFile: 'Source File',
      outputFile: 'Output File',
      replaceCountries: 'Replace Country Codes',
      replaceDescription: 'Replace account holder country codes with your allowed partner jurisdictions',
      replaceInfoText: 'This tool will replace all ResCountryCode values in account holder records with countries from your Partner Jurisdictions settings. Countries not in your allowed list will be mapped to allowed ones.',
      currentAllowedCountries: 'Current allowed countries',
      convertToTestMode: 'Convert to Test Mode',
      testModeDescription: 'Changes DocTypeIndic: OECD1→OECD11, OECD2→OECD12, OECD3→OECD13',
      noneConfigured: 'None configured',
      processingFile: 'Processing File...',
      replacementComplete: 'Replacement Complete'
    },

    // Diff Viewer
    diff: {
      title: 'XML Comparison',
      original: 'Original',
      modified: 'Modified',
      load: 'Load',
      swap: 'Swap files',
      clear: 'Clear all',
      copySummary: 'Copy summary',
      sideBySide: 'Side by Side',
      inline: 'Inline',
      noFileSelected: 'No file selected',
      loadFiles: 'Load two XML files to compare',
      originalFile: 'Original file',
      modifiedFile: 'Modified file',
      notLoaded: 'not loaded'
    },

    // Misc UI
    ui: {
      files: 'File(s)',
      needTemplate: 'Need a template?',
      downloadTemplate: 'Download the template',
      csvPreview: 'CSV Preview',
      previewDownload: 'Preview & Download Template',
      viewTemplate: 'View the required format',
      oneReportPer: 'One report per tax jurisdiction',
      companiesInEach: 'Companies in each jurisdiction',
      alwaysUSForFATCA: 'Always US for FATCA',
      partnerJurisdiction: 'Partner jurisdiction to exchange with',
      autoGeneratedIfEmpty: 'Auto-generated if empty',
      cbcCsvTemplateDesc: 'Download the CBC CSV template with example data',
      crsCsvTemplateDesc: 'View the required CSV format and download a template file for CRS 701 data.',
      uploadCrsCorrection: 'Upload a valid CRS701 (new) XML file to generate corrections (OECD2) or deletions (OECD3).',
      uploadFatcaCorrection: 'Upload a valid FATCA XML file to generate corrections (FATCA2) or voids (FATCA3).',
      uploadCbcCorrection: 'Upload a valid CBC XML file to generate corrections or deletions.',
      uploadCsvCorrection: 'Upload a CSV file with DocRefId column to specify exactly which accounts to correct or delete.',
      selectCrsFile: 'Select CRS XML file (CRS701)...',
      examine: 'Examine',
      dataSource: 'Data Source',
      randomData: 'Random Data',
      uploadCsv: 'Upload CSV'
    },

    // Footer
    footer: {
      moreModulesComingSoon: 'More modules coming soon',
      nonTaxJurisdiction: 'Non-Tax Jurisdiction',
      createdBy: 'Created by Team MDES - All Rights Reserved'
    },

    // Form validation errors
    errors: {
      mustBe2LetterISO: 'Must be 2-letter ISO code',
      mustBeAtLeast1: 'Must be at least 1',
      pleaseSelectCsvFile: 'Please select a CSV file',
      pleaseSelectXmlFile: 'Please select a CRS XML file first.',
      pleaseSelectOutputLocation: 'Please select an output location.',
      pleaseSelectCorrectionType: 'Please select correction or deletion type.',
      pleaseSelectCorrectionOption: 'Please select at least one correction or deletion option.',
      pleaseFillRequiredFields: 'Please fill in required fields first.',
      pleaseFillRequiredFieldsFATCA: 'Please fill in required fields (Transmitting Country and Output Path)',
      pleaseSelectCsvAndOutput: 'Please select a CSV file and output path',
      specifyReceivingCountry: 'For foreign exchange files, please specify the Receiving Country',
      noPartnerJurisdictions: 'No partner jurisdictions configured. Go to Settings to add countries.',
      alreadyCorrectionFile: 'This is already a correction file (CRS702). Please select a new file (CRS701).',
      fileBrowserElectronOnly: 'File browser only works in Electron app. Please run: npm run electron',
      selectValidXmlFile: 'Please select and validate a valid {module} XML file first.'
    },

    // Modal/toast messages
    modals: {
      csvValidated: 'CSV validated! {count} accounts found.',
      templateSaved: 'Template saved to: {path}',
      csvSaved: 'CSV saved to: {path}',
      correctionGenerated: 'Correction file generated!',
      correctionsCount: 'Corrections: {count}',
      deletionsCount: 'Deletions: {count}',
      fiCorrected: 'FI Corrected: Yes',
      fileProcessedSuccess: 'File processed successfully!',
      originalCountries: 'Original countries: {count}',
      replacedCountries: 'Replaced: {count}',
      docTypeConverted: 'DocTypeIndic converted to test mode',
      fatcaGeneratedSuccess: 'FATCA XML generated successfully!',
      cbcGeneratedSuccess: 'CBC XML generated successfully!',
      generatedSuccess: 'Generated successfully!',
      fileSize: 'Size: {size} MB',
      anErrorOccurred: 'An error occurred',
      validationFailed: 'Validation failed: {error}',
      failedToDownloadTemplate: 'Failed to download template: {error}',
      previewFailed: 'Preview failed: {error}',
      failedGeneric: 'Failed: {error}',
      failedToGenerateCorrection: 'Failed to generate correction: {error}',
      failedToReplaceCountryCodes: 'Failed to replace country codes: {error}',
      cbcCsvValidated: 'CBC CSV validated! {count} reports found.',
      cbcCsvValidationFailed: 'CBC CSV validation failed: {error}',
      fromCsvData: 'from CSV data',
      jurisdictionReports: '{reportCount} jurisdiction reports with {entityCount} constituent entities'
    },

    // Progress messages
    progressMessages: {
      initializingFATCA: 'Initializing FATCA generation...',
      initializingCBC: 'Initializing CBC generation...',
      initializing: 'Initializing...'
    },

    // Partner jurisdictions settings
    jurisdictions: {
      title: 'Partner Jurisdictions',
      description: 'Manage which country codes are valid for your CRS reporting. Only selected countries will be used when generating test data.',
      searchPlaceholder: 'Search countries by name or code...',
      noCountriesFound: 'No countries found or all matching countries already added',
      selectedCountries: 'Selected Countries',
      resetToDefault: 'Reset to Default',
      noCountriesSelected: 'No countries selected',
      selectAll: 'Select All',
      clearAll: 'Clear All'
    },

    // Statistics
    stats: {
      xmlGenerated: 'XML Generated',
      csvUploaded: 'CSV Uploaded',
      csvDownloaded: 'CSV Downloaded',
      validationErrors: 'Validation Errors',
      resetAllStats: 'Reset all statistics?',
      clearAllHistory: 'Clear all history?'
    },

    // Module features
    moduleFeatures: {
      crs: ['Individual & Organisation Accounts', 'Controlling Persons', 'Corrections & Deletions', 'CSV Import/Export'],
      fatca: ['Individual & Organisation Accounts', 'Substantial Owners', 'Corrections & Deletions', 'Filer Categories'],
      cbc: ['Multiple Jurisdictions', 'Constituent Entities', 'Financial Summaries', 'Corrections & Deletions']
    },

    // Settings misc
    settingsMisc: {
      csvAutoValidateOn: 'CSV files will be validated before generating XML',
      csvAutoValidateOff: 'Validation disabled - faulty CSVs can be used to generate test XMLs with errors',
      autoUpdateOn: 'App will check for updates automatically on startup',
      autoUpdateOff: 'Updates will only be checked manually',
      updateCheckFailed: 'Update check failed',
      animationsEnable: 'Click to enable live animations',
      animationsDisable: 'Click to disable live animations',
      about: 'About',
      faultyXml: 'Faulty XML'
    },

    // History
    history: {
      noFilesGenerated: 'No files generated yet'
    },

    // Correction options
    correctionLabels: {
      accountBalance: 'Account Balance',
      usingTestIndicators: 'Using OECD11/12/13 (test data indicators)',
      usingProdIndicators: 'Using OECD1/2/3 (production data indicators)'
    },

    // Update section
    updates: {
      title: 'Updates & Version',
      autoUpdate: 'Auto-Update',
      checkForUpdates: 'Check for Updates',
      checking: 'Checking...',
      downloading: 'Downloading update...',
      readyToInstall: 'Update ready to install',
      installAndRestart: 'Install & Restart',
      upToDate: 'Up to date',
      version: 'Version',
      updateAvailable: 'Update available: v{version}',
      downloadProgress: 'Download progress: {percent}%',
      whatsNew: "What's New in v1.1.1",
      changelog: [
        'Fixed missing Spanish translation for "No files generated yet"',
        'All history page text now properly translates in all languages',
        'Test update to verify auto-updater functionality'
      ]
    }
  },
  
  nl: {
    // App
    appTitle: 'MDES XML Studio',
    selectModule: 'Selecteer een Module',
    
    // Modules
    modules: {
      crs: 'CRS',
      fatca: 'FATCA',
      cbc: 'CBC'
    },
    moduleDescriptions: {
      crs: 'Common Reporting Standard',
      fatca: 'Foreign Account Tax Compliance Act',
      cbc: 'Country-by-Country Rapportage'
    },
    
    // Navigation
    nav: {
      home: 'Start',
      generator: 'Generator',
      validator: 'Validator',
      correction: 'Correctie',
      history: 'Geschiedenis',
      settings: 'Instellingen',
      help: 'Help'
    },
    
    // Actions
    actions: {
      generate: 'Genereren',
      validate: 'Valideren',
      save: 'Opslaan',
      export: 'Exporteren',
      import: 'Importeren',
      cancel: 'Annuleren',
      confirm: 'Bevestigen',
      delete: 'Verwijderen',
      edit: 'Bewerken',
      preview: 'Voorbeeld',
      download: 'Downloaden',
      upload: 'Uploaden',
      browse: 'Bladeren',
      clear: 'Wissen',
      reset: 'Resetten',
      apply: 'Toepassen',
      close: 'Sluiten',
      back: 'Terug',
      next: 'Volgende',
      finish: 'Voltooien',
      generateCRS: 'CRS XML Bestand Genereren',
      generateFATCA: 'FATCA XML Genereren',
      generateCBC: 'CBC XML Genereren',
      generatingCRS: 'CRS XML Genereren...',
      generatingFATCA: 'FATCA XML Genereren...',
      generatingCBC: 'CBC XML Genereren...',
      processing: 'Verwerken...',
      downloadCSV: 'CSV Downloaden',
      preview: 'Voorbeeld',
      close: 'Sluiten',
      generate: 'Genereren',
      open: 'Openen'
    },
    
    // Form labels
    form: {
      sendingCountry: 'Verzendend Land',
      receivingCountry: 'Ontvangend Land',
      taxYear: 'Belastingjaar',
      reportingFI: 'Rapporterende Financiële Instelling',
      numFIs: 'Aantal Financiële Instellingen',
      individualAccounts: 'Individuele Rekeningen',
      organisationAccounts: 'Organisatie Rekeningen',
      controllingPersons: 'Uiteindelijk Belanghebbenden per Organisatie',
      outputFile: 'Uitvoerbestand',
      inputFile: 'Invoerbestand',
      csvFile: 'CSV Bestand',
      xmlFile: 'XML Bestand',
      messageHeader: 'Berichtkop',
      fatcaMessageHeader: 'FATCA Berichtkop',
      cbcMessageHeader: 'CBC Berichtkop',
      sendingCompanyGIIN: 'Verzendend Bedrijf GIIN',
      sendingEntityTIN: 'Verzendende Entiteit TIN',
      transmittingCountry: 'Verzendend Land',
      reportingPeriod: 'Rapportageperiode (Jaar)',
      accountConfiguration: 'Rekeningconfiguratie',
      substantialOwners: 'Substantiële Eigenaren per Org',
      filerCategory: 'Indienercategorie',
      testModeLabel: 'Testmodus',
      fatcaTestMode: 'Testmodus (FATCA11-14 indicatoren)',
      cbcTestMode: 'Testmodus (OECD11-13 indicatoren)',
      crsTestMode: 'Testmodus',
      reportingEntity: 'Rapporterende Entiteit (MNE)',
      cbcFileType: 'CBC Bestandstype',
      domesticFiling: 'Binnenlandse Indiening',
      foreignExchange: 'Buitenlandse Uitwisseling',
      domesticFilingDesc: 'Bestand ingediend bij uw lokale belastingdienst. Ontvangend land zal hetzelfde zijn als het verzendende land.',
      foreignExchangeDesc: 'Bestand voor automatische uitwisseling met buitenlandse belastingdiensten. U moet het ontvangende land (partnerjurisdictie) specificeren.',
      mneGroupName: 'MNE Groepsnaam',
      reportingEntityName: 'Rapporterende Entiteitsnaam',
      reportingRole: 'Rapportagerol',
      cbcReportConfiguration: 'CBC Rapportconfiguratie',
      numJurisdictionReports: 'Aantal Jurisdictierapporten',
      constEntitiesPerReport: 'Samenstellende Entiteiten per Rapport',
      fileSize: 'Bestandsgrooteconfiguratie',
      dataSource: 'Gegevensbron',
      randomData: 'Willekeurige Gegevens',
      uploadCSV: 'CSV Uploaden',
      selectOutputLocation: 'Selecteer uitvoerbestandslocatie...',
      autoGenerated: 'Automatisch gegenereerd indien leeg'
    },
    
    // Messages
    messages: {
      generating: 'Bezig met genereren...',
      validating: 'Bezig met valideren...',
      success: 'Geslaagd!',
      error: 'Fout',
      warning: 'Waarschuwing',
      info: 'Informatie',
      fileGenerated: 'Bestand succesvol gegenereerd',
      validationPassed: 'Validatie geslaagd',
      validationFailed: 'Validatie mislukt',
      noFileSelected: 'Geen bestand geselecteerd',
      invalidInput: 'Ongeldige invoer',
      requiredField: 'Dit veld is verplicht',
      confirmDelete: 'Weet u zeker dat u dit wilt verwijderen?',
      unsavedChanges: 'U heeft niet-opgeslagen wijzigingen'
    },
    
    // Settings
    settings: {
      title: 'Instellingen',
      theme: 'Thema',
      language: 'Taal',
      autoSave: 'Automatisch opslaan',
      showTips: 'Tips tonen',
      recentFiles: 'Recente bestanden',
      partnerJurisdictions: 'Partner Jurisdicties',
      keyboardShortcuts: 'Sneltoetsen',
      appearance: 'Uiterlijk',
      general: 'Algemeen'
    },
    
    // History
    history: {
      title: 'Generatie Geschiedenis',
      noHistory: 'Nog geen generatie geschiedenis',
      clearHistory: 'Geschiedenis Wissen',
      totalGenerated: 'Totaal Gegenereerd',
      totalAccounts: 'Totaal Rekeningen',
      lastGeneration: 'Laatste Generatie'
    },
    
    // Recent files
    recentFiles: {
      title: 'Recente Bestanden',
      noFiles: 'Geen recente bestanden',
      clear: 'Recente bestanden wissen',
      open: 'Openen',
      remove: 'Verwijderen uit lijst'
    },
    
    // Profiles
    profiles: {
      title: 'Opgeslagen Profielen',
      save: 'Profiel Opslaan',
      load: 'Profiel Laden',
      delete: 'Profiel Verwijderen',
      name: 'Profielnaam',
      noProfiles: 'Geen opgeslagen profielen',
      saveSuccess: 'Profiel succesvol opgeslagen',
      loadSuccess: 'Profiel succesvol geladen'
    },
    
    // Validation
    validation: {
      title: 'Validatie Resultaten',
      valid: 'Geldig',
      invalid: 'Ongeldig',
      errors: 'Fouten',
      warnings: 'Waarschuwingen',
      details: 'Details'
    },
    
    // Batch
    batch: {
      title: 'Batch Verwerking',
      addFiles: 'Bestanden Toevoegen',
      removeAll: 'Alles Verwijderen',
      processAll: 'Alles Verwerken',
      progress: 'Voortgang',
      completed: 'Voltooid',
      failed: 'Mislukt',
      pending: 'Wachtend',
      addFilesPrompt: 'Bestanden toevoegen om in batch te genereren:',
      filesQueued: 'bestand(en) in wachtrij',
      clearAll: 'Alles Wissen',
      crsFile: 'CRS Bestand',
      fatcaFile: 'FATCA Bestand',
      cbcFile: 'CBC Bestand',
      outputLocation: 'Uitvoerlocatie',
      selectOutputFolder: 'Selecteer uitvoermap...',
      batchComplete: 'Batch Voltooid',
      succeeded: 'geslaagd',
      ind: 'Ind',
      org: 'Org',
      reports: 'Rapporten'
    },
    
    // Diff
    diff: {
      title: 'XML Vergelijking',
      original: 'Origineel',
      modified: 'Gewijzigd',
      differences: 'Verschillen',
      noDifferences: 'Geen verschillen gevonden',
      added: 'Toegevoegd',
      removed: 'Verwijderd',
      changed: 'Gewijzigd'
    },
    
    // Help
    help: {
      title: 'Help',
      shortcuts: 'Sneltoetsen',
      documentation: 'Documentatie',
      about: 'Over'
    },

    // Dashboard
    dashboard: {
      title: 'Dashboard',
      welcome: 'Welkom',
      quickActions: 'Snelle Acties',
      statistics: 'Statistieken',
      recentActivity: 'Recente Activiteit'
    },

    // Templates
    templates: {
      title: 'Sjabloonbibliotheek',
      select: 'Sjabloon Selecteren',
      apply: 'Sjabloon Toepassen',
      basicIndividual: 'Basis Individuele Rekeningen',
      basicOrg: 'Basis Organisatie Rekeningen',
      mixed: 'Gemengde Rekeningtypen',
      correction: 'Correctiebestand',
      largeDataset: 'Grote Dataset'
    },

    // Common
    common: {
      loading: 'Laden...',
      saving: 'Opslaan...',
      processing: 'Verwerken...',
      done: 'Klaar',
      yes: 'Ja',
      no: 'Nee',
      ok: 'OK',
      or: 'of',
      and: 'en',
      all: 'Alles',
      none: 'Geen',
      select: 'Selecteren',
      selected: 'Geselecteerd',
      search: 'Zoeken',
      filter: 'Filteren',
      sort: 'Sorteren',
      more: 'Meer',
      less: 'Minder',
      show: 'Tonen',
      hide: 'Verbergen',
      expand: 'Uitvouwen',
      collapse: 'Invouwen',
      refresh: 'Vernieuwen',
      retry: 'Opnieuw proberen',
      copy: 'Kopiëren',
      copied: 'Gekopieerd!',
      paste: 'Plakken',
      cut: 'Knippen',
      undo: 'Ongedaan maken',
      redo: 'Opnieuw doen',
      browse: 'Bladeren',
      output: 'Uitvoer',
      selectOutputLocation: 'Selecteer uitvoerbestandslocatie...',
      selectFolder: 'Selecteer Map',
      generating: 'Genereren',
      testMode: 'Testmodus'
    },

    // Corrections
    corrections: {
      title: 'Correcties',
      generateCRS: 'CRS702 Correctiebestanden Genereren',
      generateFATCA: 'FATCA Correctiebestanden Genereren',
      generateCBC: 'CBC Correctiebestanden Genereren',
      sourceXmlFile: 'Bron XML Bestand',
      fromXmlFile: 'Vanuit XML Bestand',
      fromCsvFile: 'Vanuit CSV Bestand',
      selectXmlFile: 'Selecteer XML bestand...',
      correctionType: 'Correctietype',
      generateCorrection: 'Correctiebestand Genereren',
      correctionCsvFile: 'Correctie CSV Bestand',
      requiredCsvFormat: 'Vereist CSV Formaat',
      viewCsvTemplate: 'CSV Sjabloon Bekijken',
      selectCorrectionCsv: 'Selecteer correctie CSV bestand...',
      correctionOptions: 'Correctieopties',
      cbcCorrectionOptions: 'CBC Correctieopties',
      correctionOECD2: 'Correctie (OECD2)',
      deletionOECD3: 'Verwijdering (OECD3)',
      modifyExisting: 'Bestaande rapportgegevens wijzigen',
      deleteExisting: 'Bestaande rapportgegevens verwijderen',
      validFile: 'Geldig Bestand',
      validationFailed: 'Validatie Mislukt'
    },

    // Tools
    tools: {
      title: 'Hulpmiddelen',
      countryCodeReplacer: 'Landcode Vervanger',
      sourceFile: 'Bronbestand',
      outputFile: 'Uitvoerbestand',
      replaceCountries: 'Landcodes Vervangen',
      replaceDescription: 'Vervang landcodes van rekeninghouders met uw toegestane partnerjurisdicties',
      replaceInfoText: 'Dit hulpmiddel vervangt alle ResCountryCode waarden in rekeninghouderrecords met landen uit uw Partner Jurisdicties instellingen. Landen die niet in uw toegestane lijst staan worden toegewezen aan toegestane landen.',
      currentAllowedCountries: 'Huidige toegestane landen',
      convertToTestMode: 'Converteren naar Testmodus',
      testModeDescription: 'Wijzigt DocTypeIndic: OECD1→OECD11, OECD2→OECD12, OECD3→OECD13',
      noneConfigured: 'Geen geconfigureerd',
      processingFile: 'Bestand verwerken...',
      replacementComplete: 'Vervanging Voltooid'
    },

    // Diff Viewer
    diff: {
      title: 'XML Vergelijking',
      original: 'Origineel',
      modified: 'Gewijzigd',
      load: 'Laden',
      swap: 'Bestanden verwisselen',
      clear: 'Alles wissen',
      copySummary: 'Samenvatting kopiëren',
      sideBySide: 'Naast Elkaar',
      inline: 'Inline',
      noFileSelected: 'Geen bestand geselecteerd',
      loadFiles: 'Laad twee XML bestanden om te vergelijken',
      originalFile: 'Origineel bestand',
      modifiedFile: 'Gewijzigd bestand',
      notLoaded: 'niet geladen'
    },

    // Misc UI
    ui: {
      files: 'Bestand(en)',
      needTemplate: 'Sjabloon nodig?',
      downloadTemplate: 'Download het sjabloon',
      csvPreview: 'CSV Voorbeeld',
      previewDownload: 'Voorbeeld & Sjabloon Downloaden',
      viewTemplate: 'Bekijk het vereiste formaat',
      oneReportPer: 'Eén rapport per belastingjurisdictie',
      companiesInEach: 'Bedrijven in elke jurisdictie',
      alwaysUSForFATCA: 'Altijd VS voor FATCA',
      partnerJurisdiction: 'Partnerjurisdictie voor uitwisseling',
      autoGeneratedIfEmpty: 'Automatisch gegenereerd indien leeg',
      cbcCsvTemplateDesc: 'Download het CBC CSV sjabloon met voorbeeldgegevens',
      crsCsvTemplateDesc: 'Bekijk het vereiste CSV formaat en download een sjabloonbestand voor CRS 701 gegevens.',
      uploadCrsCorrection: 'Upload een geldig CRS701 (nieuw) XML bestand om correcties (OECD2) of verwijderingen (OECD3) te genereren.',
      uploadFatcaCorrection: 'Upload een geldig FATCA XML bestand om correcties (FATCA2) of annuleringen (FATCA3) te genereren.',
      uploadCbcCorrection: 'Upload een geldig CBC XML bestand om correcties of verwijderingen te genereren.',
      uploadCsvCorrection: 'Upload een CSV bestand met DocRefId kolom om exact te specificeren welke rekeningen gecorrigeerd of verwijderd moeten worden.',
      selectCrsFile: 'Selecteer CRS XML bestand (CRS701)...',
      examine: 'Onderzoeken',
      dataSource: 'Gegevensbron',
      randomData: 'Willekeurige Gegevens',
      uploadCsv: 'CSV Uploaden'
    },

    // Footer
    footer: {
      moreModulesComingSoon: 'Meer modules binnenkort beschikbaar',
      nonTaxJurisdiction: 'Niet-Belasting Jurisdictie',
      createdBy: 'Gemaakt door Team MDES - Alle Rechten Voorbehouden'
    },

    // Form validation errors
    errors: {
      mustBe2LetterISO: 'Moet een 2-letterige ISO code zijn',
      mustBeAtLeast1: 'Moet minimaal 1 zijn',
      pleaseSelectCsvFile: 'Selecteer een CSV bestand',
      pleaseSelectXmlFile: 'Selecteer eerst een CRS XML bestand.',
      pleaseSelectOutputLocation: 'Selecteer een uitvoerlocatie.',
      pleaseSelectCorrectionType: 'Selecteer correctie- of verwijderingstype.',
      pleaseSelectCorrectionOption: 'Selecteer minimaal één correctie- of verwijderingsoptie.',
      pleaseFillRequiredFields: 'Vul eerst de verplichte velden in.',
      pleaseFillRequiredFieldsFATCA: 'Vul de verplichte velden in (Verzendend Land en Uitvoerpad)',
      pleaseSelectCsvAndOutput: 'Selecteer een CSV bestand en uitvoerpad',
      specifyReceivingCountry: 'Voor buitenlandse uitwisselingsbestanden, specificeer het Ontvangende Land',
      noPartnerJurisdictions: 'Geen partnerjurisdicties geconfigureerd. Ga naar Instellingen om landen toe te voegen.',
      alreadyCorrectionFile: 'Dit is al een correctiebestand (CRS702). Selecteer een nieuw bestand (CRS701).',
      fileBrowserElectronOnly: 'Bestandsbrowser werkt alleen in Electron app. Voer uit: npm run electron',
      selectValidXmlFile: 'Selecteer en valideer eerst een geldig {module} XML bestand.'
    },

    // Modal/toast messages
    modals: {
      csvValidated: 'CSV gevalideerd! {count} rekeningen gevonden.',
      templateSaved: 'Sjabloon opgeslagen naar: {path}',
      csvSaved: 'CSV opgeslagen naar: {path}',
      correctionGenerated: 'Correctiebestand gegenereerd!',
      correctionsCount: 'Correcties: {count}',
      deletionsCount: 'Verwijderingen: {count}',
      fiCorrected: 'FI Gecorrigeerd: Ja',
      fileProcessedSuccess: 'Bestand succesvol verwerkt!',
      originalCountries: 'Originele landen: {count}',
      replacedCountries: 'Vervangen: {count}',
      docTypeConverted: 'DocTypeIndic geconverteerd naar testmodus',
      fatcaGeneratedSuccess: 'FATCA XML succesvol gegenereerd!',
      cbcGeneratedSuccess: 'CBC XML succesvol gegenereerd!',
      generatedSuccess: 'Succesvol gegenereerd!',
      fileSize: 'Grootte: {size} MB',
      anErrorOccurred: 'Er is een fout opgetreden',
      validationFailed: 'Validatie mislukt: {error}',
      failedToDownloadTemplate: 'Sjabloon downloaden mislukt: {error}',
      previewFailed: 'Voorbeeld mislukt: {error}',
      failedGeneric: 'Mislukt: {error}',
      failedToGenerateCorrection: 'Correctie genereren mislukt: {error}',
      failedToReplaceCountryCodes: 'Landcodes vervangen mislukt: {error}',
      cbcCsvValidated: 'CBC CSV gevalideerd! {count} rapporten gevonden.',
      cbcCsvValidationFailed: 'CBC CSV validatie mislukt: {error}',
      fromCsvData: 'vanuit CSV gegevens',
      jurisdictionReports: '{reportCount} jurisdictierapporten met {entityCount} samenstellende entiteiten'
    },

    // Progress messages
    progressMessages: {
      initializingFATCA: 'FATCA generatie initialiseren...',
      initializingCBC: 'CBC generatie initialiseren...',
      initializing: 'Initialiseren...'
    },

    // Partner jurisdictions settings
    jurisdictions: {
      title: 'Partner Jurisdicties',
      description: 'Beheer welke landcodes geldig zijn voor uw CRS rapportage. Alleen geselecteerde landen worden gebruikt bij het genereren van testgegevens.',
      searchPlaceholder: 'Zoek landen op naam of code...',
      noCountriesFound: 'Geen landen gevonden of alle overeenkomende landen al toegevoegd',
      selectedCountries: 'Geselecteerde Landen',
      resetToDefault: 'Standaard Herstellen',
      noCountriesSelected: 'Geen landen geselecteerd',
      selectAll: 'Alles Selecteren',
      clearAll: 'Alles Wissen'
    },

    // Statistics
    stats: {
      xmlGenerated: 'XML Gegenereerd',
      csvUploaded: 'CSV Geüpload',
      csvDownloaded: 'CSV Gedownload',
      validationErrors: 'Validatiefouten',
      resetAllStats: 'Alle statistieken resetten?',
      clearAllHistory: 'Alle geschiedenis wissen?'
    },

    // Module features
    moduleFeatures: {
      crs: ['Individuele & Organisatie Rekeningen', 'Uiteindelijk Belanghebbenden', 'Correcties & Verwijderingen', 'CSV Import/Export'],
      fatca: ['Individuele & Organisatie Rekeningen', 'Substantiële Eigenaren', 'Correcties & Verwijderingen', 'Indienercategorieën'],
      cbc: ['Meerdere Jurisdicties', 'Samenstellende Entiteiten', 'Financiële Overzichten', 'Correcties & Verwijderingen']
    },

    // Settings misc
    settingsMisc: {
      csvAutoValidateOn: 'CSV bestanden worden gevalideerd voor het genereren van XML',
      csvAutoValidateOff: 'Validatie uitgeschakeld - foutieve CSVs kunnen gebruikt worden om test XMLs met fouten te genereren',
      autoUpdateOn: 'App controleert automatisch op updates bij het opstarten',
      autoUpdateOff: 'Updates worden alleen handmatig gecontroleerd',
      updateCheckFailed: 'Updatecontrole mislukt',
      animationsEnable: 'Klik om live animaties in te schakelen',
      animationsDisable: 'Klik om live animaties uit te schakelen',
      about: 'Over',
      faultyXml: 'Foutieve XML'
    },

    // History
    history: {
      noFilesGenerated: 'Nog geen bestanden gegenereerd'
    },

    // Correction options
    correctionLabels: {
      accountBalance: 'Rekeningsaldo',
      usingTestIndicators: 'Gebruik OECD11/12/13 (test data indicatoren)',
      usingProdIndicators: 'Gebruik OECD1/2/3 (productie data indicatoren)'
    },

    // Update section
    updates: {
      title: 'Updates & Versie',
      autoUpdate: 'Automatisch Updaten',
      checkForUpdates: 'Controleren op Updates',
      checking: 'Controleren...',
      downloading: 'Update downloaden...',
      readyToInstall: 'Update klaar om te installeren',
      installAndRestart: 'Installeren & Herstarten',
      upToDate: 'Up-to-date',
      version: 'Versie',
      updateAvailable: 'Update beschikbaar: v{version}',
      downloadProgress: 'Downloadvoortgang: {percent}%',
      whatsNew: 'Wat is nieuw in v1.1.1',
      changelog: [
        'Ontbrekende Spaanse vertaling voor "Nog geen bestanden gegenereerd" gefixt',
        'Alle geschiedenispagina-tekst vertaalt nu correct in alle talen',
        'Testupdate om auto-updater functionaliteit te verifiëren'
      ]
    }
  },

  // Spanish translations
  es: {
    // App
    appTitle: 'MDES XML Studio',
    selectModule: 'Seleccionar Módulo',
    
    // Modules
    modules: {
      crs: 'CRS',
      fatca: 'FATCA',
      cbc: 'CBC'
    },
    moduleDescriptions: {
      crs: 'Estándar Común de Reporte',
      fatca: 'Ley de Cumplimiento Fiscal de Cuentas Extranjeras',
      cbc: 'Informe País por País'
    },
    
    // Navigation
    nav: {
      home: 'Inicio',
      generator: 'Generador',
      validator: 'Validador',
      correction: 'Corrección',
      history: 'Historial',
      settings: 'Configuración',
      help: 'Ayuda'
    },
    
    // Actions
    actions: {
      generate: 'Generar',
      validate: 'Validar',
      save: 'Guardar',
      export: 'Exportar',
      import: 'Importar',
      cancel: 'Cancelar',
      confirm: 'Confirmar',
      delete: 'Eliminar',
      edit: 'Editar',
      preview: 'Vista previa',
      download: 'Descargar',
      upload: 'Subir',
      browse: 'Examinar',
      clear: 'Limpiar',
      reset: 'Restablecer',
      apply: 'Aplicar',
      close: 'Cerrar',
      back: 'Atrás',
      next: 'Siguiente',
      finish: 'Finalizar',
      generateCRS: 'Generar Archivo XML CRS',
      generateFATCA: 'Generar XML FATCA',
      generateCBC: 'Generar XML CBC',
      generatingCRS: 'Generando XML CRS...',
      generatingFATCA: 'Generando XML FATCA...',
      generatingCBC: 'Generando XML CBC...',
      processing: 'Procesando...',
      open: 'Abrir'
    },
    
    // Form labels
    form: {
      sendingCountry: 'País Emisor',
      receivingCountry: 'País Receptor',
      taxYear: 'Año Fiscal',
      reportingFI: 'Institución Financiera Reportante',
      numFIs: 'Número de Instituciones Financieras',
      individualAccounts: 'Cuentas Individuales',
      organisationAccounts: 'Cuentas de Organizaciones',
      controllingPersons: 'Personas Controladoras por Organización',
      outputFile: 'Archivo de Salida',
      inputFile: 'Archivo de Entrada',
      csvFile: 'Archivo CSV',
      xmlFile: 'Archivo XML',
      messageHeader: 'Encabezado del Mensaje',
      fatcaMessageHeader: 'Encabezado del Mensaje FATCA',
      cbcMessageHeader: 'Encabezado del Mensaje CBC',
      sendingCompanyGIIN: 'GIIN de la Empresa Emisora',
      sendingEntityTIN: 'TIN de la Entidad Emisora',
      transmittingCountry: 'País Transmisor',
      reportingPeriod: 'Período de Reporte (Año)',
      accountConfiguration: 'Configuración de Cuentas',
      substantialOwners: 'Propietarios Sustanciales por Org',
      filerCategory: 'Categoría de Declarante',
      testModeLabel: 'Modo de Prueba',
      fatcaTestMode: 'Modo de Prueba (indicadores FATCA11-14)',
      cbcTestMode: 'Modo de Prueba (indicadores OECD11-13)',
      crsTestMode: 'Modo de Prueba',
      reportingEntity: 'Entidad Informante (MNE)',
      cbcFileType: 'Tipo de Archivo CBC',
      domesticFiling: 'Presentación Nacional',
      foreignExchange: 'Intercambio Extranjero',
      domesticFilingDesc: 'Archivo presentado a su autoridad fiscal local. El país receptor será el mismo que el país transmisor.',
      foreignExchangeDesc: 'Archivo para intercambio automático con autoridades fiscales extranjeras. Debe especificar el país receptor (jurisdicción asociada).',
      mneGroupName: 'Nombre del Grupo MNE',
      reportingEntityName: 'Nombre de la Entidad Reportante',
      reportingRole: 'Rol de Reporte',
      cbcReportConfiguration: 'Configuración del Informe CBC',
      numJurisdictionReports: 'Número de Informes de Jurisdicción',
      constEntitiesPerReport: 'Entidades Constituyentes por Informe',
      fileSize: 'Configuración del Tamaño del Archivo',
      dataSource: 'Fuente de Datos',
      randomData: 'Datos Aleatorios',
      uploadCSV: 'Subir CSV',
      selectOutputLocation: 'Seleccionar ubicación del archivo de salida...',
      autoGenerated: 'Generado automáticamente si está vacío'
    },
    
    // Messages
    messages: {
      generating: 'Generando...',
      validating: 'Validando...',
      success: '¡Éxito!',
      error: 'Error',
      warning: 'Advertencia',
      info: 'Información',
      fileGenerated: 'Archivo generado correctamente',
      validationPassed: 'Validación exitosa',
      validationFailed: 'Validación fallida',
      noFileSelected: 'Ningún archivo seleccionado',
      invalidInput: 'Entrada no válida',
      requiredField: 'Este campo es obligatorio',
      confirmDelete: '¿Está seguro de que desea eliminar esto?',
      unsavedChanges: 'Tiene cambios sin guardar'
    },
    
    // Settings
    settings: {
      title: 'Configuración',
      theme: 'Tema',
      language: 'Idioma',
      autoSave: 'Guardado automático',
      showTips: 'Mostrar consejos',
      recentFiles: 'Archivos recientes',
      partnerJurisdictions: 'Jurisdicciones Asociadas',
      keyboardShortcuts: 'Atajos de Teclado',
      appearance: 'Apariencia',
      darkMode: 'Modo Oscuro',
      lightMode: 'Modo Claro',
      general: 'General',
      advanced: 'Avanzado'
    },
    
    // History
    history: {
      title: 'Historial de Generación',
      noHistory: 'Sin historial de generación',
      clearHistory: 'Limpiar Historial',
      totalGenerated: 'Total Generado',
      totalAccounts: 'Total de Cuentas',
      lastGeneration: 'Última Generación'
    },
    
    // Recent files
    recentFiles: {
      title: 'Archivos Recientes',
      noFiles: 'Sin archivos recientes',
      clear: 'Limpiar archivos recientes',
      open: 'Abrir',
      remove: 'Quitar de la lista'
    },
    
    // Profiles
    profiles: {
      title: 'Perfiles Guardados',
      save: 'Guardar Perfil',
      load: 'Cargar Perfil',
      delete: 'Eliminar Perfil',
      name: 'Nombre del Perfil',
      noProfiles: 'Sin perfiles guardados',
      saveSuccess: 'Perfil guardado correctamente',
      loadSuccess: 'Perfil cargado correctamente'
    },
    
    // Validation
    validation: {
      title: 'Resultados de Validación',
      valid: 'Válido',
      invalid: 'No válido',
      errors: 'Errores',
      warnings: 'Advertencias',
      details: 'Detalles'
    },
    
    // Batch
    batch: {
      title: 'Procesamiento por Lotes',
      addFiles: 'Agregar Archivos',
      removeAll: 'Eliminar Todo',
      processAll: 'Procesar Todo',
      progress: 'Progreso',
      completed: 'Completado',
      failed: 'Fallido',
      pending: 'Pendiente',
      addFilesPrompt: 'Agregar archivos para generar por lotes:',
      filesQueued: 'archivo(s) en cola',
      clearAll: 'Limpiar Todo',
      crsFile: 'Archivo CRS',
      fatcaFile: 'Archivo FATCA',
      cbcFile: 'Archivo CBC',
      outputLocation: 'Ubicación de Salida',
      selectOutputFolder: 'Seleccionar carpeta de salida...',
      batchComplete: 'Lote Completado',
      succeeded: 'exitoso',
      ind: 'Ind',
      org: 'Org',
      reports: 'Informes'
    },
    
    // Diff
    diff: {
      title: 'Comparación XML',
      original: 'Original',
      modified: 'Modificado',
      differences: 'Diferencias',
      noDifferences: 'No se encontraron diferencias',
      added: 'Agregado',
      removed: 'Eliminado',
      changed: 'Modificado'
    },
    
    // Help
    help: {
      title: 'Ayuda',
      shortcuts: 'Atajos de Teclado',
      documentation: 'Documentación',
      about: 'Acerca de'
    },

    // Dashboard
    dashboard: {
      title: 'Panel de Control',
      welcome: 'Bienvenido',
      quickActions: 'Acciones Rápidas',
      statistics: 'Estadísticas',
      recentActivity: 'Actividad Reciente'
    },

    // Templates
    templates: {
      title: 'Biblioteca de Plantillas',
      select: 'Seleccionar Plantilla',
      apply: 'Aplicar Plantilla',
      basicIndividual: 'Cuentas Individuales Básicas',
      basicOrg: 'Cuentas de Organizaciones Básicas',
      mixed: 'Tipos de Cuenta Mixtos',
      correction: 'Archivo de Corrección',
      largeDataset: 'Conjunto de Datos Grande'
    },

    // Common
    common: {
      loading: 'Cargando...',
      saving: 'Guardando...',
      processing: 'Procesando...',
      done: 'Hecho',
      yes: 'Sí',
      no: 'No',
      ok: 'Aceptar',
      or: 'o',
      and: 'y',
      all: 'Todo',
      none: 'Ninguno',
      select: 'Seleccionar',
      selected: 'Seleccionado',
      search: 'Buscar',
      filter: 'Filtrar',
      sort: 'Ordenar',
      more: 'Más',
      less: 'Menos',
      show: 'Mostrar',
      hide: 'Ocultar',
      expand: 'Expandir',
      collapse: 'Contraer',
      refresh: 'Actualizar',
      retry: 'Reintentar',
      copy: 'Copiar',
      copied: '¡Copiado!',
      paste: 'Pegar',
      cut: 'Cortar',
      undo: 'Deshacer',
      redo: 'Rehacer',
      browse: 'Examinar',
      output: 'Salida',
      selectOutputLocation: 'Seleccionar ubicación del archivo de salida...',
      selectFolder: 'Seleccionar Carpeta',
      generating: 'Generando',
      testMode: 'Modo de Prueba'
    },

    // Corrections
    corrections: {
      title: 'Correcciones',
      generateCRS: 'Generar Archivos de Corrección CRS702',
      generateFATCA: 'Generar Archivos de Corrección FATCA',
      generateCBC: 'Generar Archivos de Corrección CBC',
      sourceXmlFile: 'Archivo XML de Origen',
      fromXmlFile: 'Desde Archivo XML',
      fromCsvFile: 'Desde Archivo CSV',
      selectXmlFile: 'Seleccionar archivo XML...',
      correctionType: 'Tipo de Corrección',
      generateCorrection: 'Generar Archivo de Corrección',
      correctionCsvFile: 'Archivo CSV de Corrección',
      requiredCsvFormat: 'Formato CSV Requerido',
      viewCsvTemplate: 'Ver Plantilla CSV',
      selectCorrectionCsv: 'Seleccionar archivo CSV de corrección...',
      correctionOptions: 'Opciones de Corrección',
      cbcCorrectionOptions: 'Opciones de Corrección CBC',
      correctionOECD2: 'Corrección (OECD2)',
      deletionOECD3: 'Eliminación (OECD3)',
      modifyExisting: 'Modificar datos de informe existentes',
      deleteExisting: 'Eliminar datos de informe existentes',
      validFile: 'Archivo Válido',
      validationFailed: 'Validación Fallida'
    },

    // Tools
    tools: {
      title: 'Herramientas',
      countryCodeReplacer: 'Reemplazador de Códigos de País',
      sourceFile: 'Archivo de Origen',
      outputFile: 'Archivo de Salida',
      replaceCountries: 'Reemplazar Códigos de País',
      replaceDescription: 'Reemplazar códigos de país de titulares de cuentas con sus jurisdicciones asociadas permitidas',
      replaceInfoText: 'Esta herramienta reemplazará todos los valores ResCountryCode en los registros de titulares de cuentas con países de su configuración de Jurisdicciones Asociadas. Los países que no estén en su lista permitida serán mapeados a países permitidos.',
      currentAllowedCountries: 'Países permitidos actuales',
      convertToTestMode: 'Convertir a Modo de Prueba',
      testModeDescription: 'Cambia DocTypeIndic: OECD1→OECD11, OECD2→OECD12, OECD3→OECD13',
      noneConfigured: 'Ninguno configurado',
      processingFile: 'Procesando archivo...',
      replacementComplete: 'Reemplazo Completado'
    },

    // Diff Viewer
    diff: {
      title: 'Comparación XML',
      original: 'Original',
      modified: 'Modificado',
      load: 'Cargar',
      swap: 'Intercambiar archivos',
      clear: 'Limpiar todo',
      copySummary: 'Copiar resumen',
      sideBySide: 'Lado a Lado',
      inline: 'En Línea',
      noFileSelected: 'Ningún archivo seleccionado',
      loadFiles: 'Cargar dos archivos XML para comparar',
      originalFile: 'Archivo original',
      modifiedFile: 'Archivo modificado',
      notLoaded: 'no cargado'
    },

    // Misc UI
    ui: {
      files: 'Archivo(s)',
      needTemplate: '¿Necesitas una plantilla?',
      downloadTemplate: 'Descargar la plantilla',
      csvPreview: 'Vista Previa CSV',
      previewDownload: 'Vista Previa y Descargar Plantilla',
      viewTemplate: 'Ver el formato requerido',
      oneReportPer: 'Un informe por jurisdicción fiscal',
      companiesInEach: 'Empresas en cada jurisdicción',
      alwaysUSForFATCA: 'Siempre EE.UU. para FATCA',
      partnerJurisdiction: 'Jurisdicción asociada para intercambio',
      autoGeneratedIfEmpty: 'Generado automáticamente si está vacío',
      cbcCsvTemplateDesc: 'Descargar la plantilla CSV de CBC con datos de ejemplo',
      crsCsvTemplateDesc: 'Ver el formato CSV requerido y descargar un archivo de plantilla para datos CRS 701.',
      uploadCrsCorrection: 'Cargar un archivo XML CRS701 (nuevo) válido para generar correcciones (OECD2) o eliminaciones (OECD3).',
      uploadFatcaCorrection: 'Cargar un archivo XML FATCA válido para generar correcciones (FATCA2) o anulaciones (FATCA3).',
      uploadCbcCorrection: 'Cargar un archivo XML CBC válido para generar correcciones o eliminaciones.',
      uploadCsvCorrection: 'Cargar un archivo CSV con columna DocRefId para especificar exactamente qué cuentas corregir o eliminar.',
      selectCrsFile: 'Seleccionar archivo XML CRS (CRS701)...',
      examine: 'Examinar',
      dataSource: 'Fuente de Datos',
      randomData: 'Datos Aleatorios',
      uploadCsv: 'Subir CSV'
    },

    // Footer
    footer: {
      moreModulesComingSoon: 'Más módulos próximamente',
      nonTaxJurisdiction: 'Jurisdicción No Fiscal',
      createdBy: 'Creado por Team MDES - Todos los Derechos Reservados'
    },

    // Form validation errors
    errors: {
      mustBe2LetterISO: 'Debe ser un código ISO de 2 letras',
      mustBeAtLeast1: 'Debe ser al menos 1',
      pleaseSelectCsvFile: 'Seleccione un archivo CSV',
      pleaseSelectXmlFile: 'Seleccione primero un archivo XML CRS.',
      pleaseSelectOutputLocation: 'Seleccione una ubicación de salida.',
      pleaseSelectCorrectionType: 'Seleccione tipo de corrección o eliminación.',
      pleaseSelectCorrectionOption: 'Seleccione al menos una opción de corrección o eliminación.',
      pleaseFillRequiredFields: 'Complete primero los campos obligatorios.',
      pleaseFillRequiredFieldsFATCA: 'Complete los campos obligatorios (País Transmisor y Ruta de Salida)',
      pleaseSelectCsvAndOutput: 'Seleccione un archivo CSV y ruta de salida',
      specifyReceivingCountry: 'Para archivos de intercambio extranjero, especifique el País Receptor',
      noPartnerJurisdictions: 'No hay jurisdicciones asociadas configuradas. Vaya a Configuración para agregar países.',
      alreadyCorrectionFile: 'Este ya es un archivo de corrección (CRS702). Seleccione un archivo nuevo (CRS701).',
      fileBrowserElectronOnly: 'El explorador de archivos solo funciona en la app Electron. Ejecute: npm run electron',
      selectValidXmlFile: 'Seleccione y valide primero un archivo XML {module} válido.'
    },

    // Modal/toast messages
    modals: {
      csvValidated: '¡CSV validado! {count} cuentas encontradas.',
      templateSaved: 'Plantilla guardada en: {path}',
      csvSaved: 'CSV guardado en: {path}',
      correctionGenerated: '¡Archivo de corrección generado!',
      correctionsCount: 'Correcciones: {count}',
      deletionsCount: 'Eliminaciones: {count}',
      fiCorrected: 'IF Corregida: Sí',
      fileProcessedSuccess: '¡Archivo procesado correctamente!',
      originalCountries: 'Países originales: {count}',
      replacedCountries: 'Reemplazados: {count}',
      docTypeConverted: 'DocTypeIndic convertido a modo de prueba',
      fatcaGeneratedSuccess: '¡XML FATCA generado correctamente!',
      cbcGeneratedSuccess: '¡XML CBC generado correctamente!',
      generatedSuccess: '¡Generado correctamente!',
      fileSize: 'Tamaño: {size} MB',
      anErrorOccurred: 'Se produjo un error',
      validationFailed: 'Validación fallida: {error}',
      failedToDownloadTemplate: 'Error al descargar plantilla: {error}',
      previewFailed: 'Vista previa fallida: {error}',
      failedGeneric: 'Error: {error}',
      failedToGenerateCorrection: 'Error al generar corrección: {error}',
      failedToReplaceCountryCodes: 'Error al reemplazar códigos de país: {error}',
      cbcCsvValidated: '¡CSV CBC validado! {count} informes encontrados.',
      cbcCsvValidationFailed: 'Validación CSV CBC fallida: {error}',
      fromCsvData: 'desde datos CSV',
      jurisdictionReports: '{reportCount} informes de jurisdicción con {entityCount} entidades constituyentes'
    },

    // Progress messages
    progressMessages: {
      initializingFATCA: 'Inicializando generación FATCA...',
      initializingCBC: 'Inicializando generación CBC...',
      initializing: 'Inicializando...'
    },

    // Partner jurisdictions settings
    jurisdictions: {
      title: 'Jurisdicciones Asociadas',
      description: 'Administre qué códigos de país son válidos para su informe CRS. Solo los países seleccionados se usarán al generar datos de prueba.',
      searchPlaceholder: 'Buscar países por nombre o código...',
      noCountriesFound: 'No se encontraron países o todos los países coincidentes ya fueron agregados',
      selectedCountries: 'Países Seleccionados',
      resetToDefault: 'Restablecer a Predeterminado',
      noCountriesSelected: 'Ningún país seleccionado',
      selectAll: 'Seleccionar Todo',
      clearAll: 'Limpiar Todo'
    },

    // Statistics
    stats: {
      xmlGenerated: 'XML Generados',
      csvUploaded: 'CSV Subidos',
      csvDownloaded: 'CSV Descargados',
      validationErrors: 'Errores de Validación',
      resetAllStats: '¿Restablecer todas las estadísticas?',
      clearAllHistory: '¿Limpiar todo el historial?'
    },

    // Module features
    moduleFeatures: {
      crs: ['Cuentas Individuales y de Organizaciones', 'Personas Controladoras', 'Correcciones y Eliminaciones', 'Importar/Exportar CSV'],
      fatca: ['Cuentas Individuales y de Organizaciones', 'Propietarios Sustanciales', 'Correcciones y Eliminaciones', 'Categorías de Declarante'],
      cbc: ['Múltiples Jurisdicciones', 'Entidades Constituyentes', 'Resúmenes Financieros', 'Correcciones y Eliminaciones']
    },

    // Settings misc
    settingsMisc: {
      csvAutoValidateOn: 'Los archivos CSV serán validados antes de generar XML',
      csvAutoValidateOff: 'Validación desactivada - CSVs defectuosos pueden usarse para generar XMLs de prueba con errores',
      autoUpdateOn: 'La app verificará actualizaciones automáticamente al iniciar',
      autoUpdateOff: 'Las actualizaciones solo se verificarán manualmente',
      updateCheckFailed: 'Verificación de actualización fallida',
      animationsEnable: 'Clic para activar animaciones en vivo',
      animationsDisable: 'Clic para desactivar animaciones en vivo',
      about: 'Acerca de',
      faultyXml: 'XML Defectuoso'
    },

    // History
    history: {
      noFilesGenerated: 'Aún no se han generado archivos'
    },

    // Correction options
    correctionLabels: {
      accountBalance: 'Saldo de Cuenta',
      usingTestIndicators: 'Usando OECD11/12/13 (indicadores de datos de prueba)',
      usingProdIndicators: 'Usando OECD1/2/3 (indicadores de datos de producción)'
    },

    // Update section
    updates: {
      title: 'Actualizaciones y Versión',
      autoUpdate: 'Actualización Automática',
      checkForUpdates: 'Buscar Actualizaciones',
      checking: 'Verificando...',
      downloading: 'Descargando actualización...',
      readyToInstall: 'Actualización lista para instalar',
      installAndRestart: 'Instalar y Reiniciar',
      upToDate: 'Actualizado',
      version: 'Versión',
      updateAvailable: 'Actualización disponible: v{version}',
      downloadProgress: 'Progreso de descarga: {percent}%',
      whatsNew: 'Novedades en v1.1.1',
      changelog: [
        'Traducción española faltante para "Aún no se han generado archivos" corregida',
        'Todo el texto de la página de historial ahora se traduce correctamente en todos los idiomas',
        'Actualización de prueba para verificar la funcionalidad del auto-updater'
      ]
    }
  }
};

/**
 * Get translation by key path
 * @param {string} lang - Language code
 * @param {string} key - Dot-separated key path (e.g., 'nav.home')
 * @param {Object} params - Optional parameters for interpolation
 */
export function t(lang, key, params = {}) {
  const keys = key.split('.');
  let value = translations[lang] || translations.en;
  
  for (const k of keys) {
    value = value?.[k];
    if (value === undefined) {
      // Fallback to English
      value = translations.en;
      for (const fallbackKey of keys) {
        value = value?.[fallbackKey];
      }
      break;
    }
  }
  
  if (Array.isArray(value)) {
    return value; // Return arrays directly (e.g., moduleFeatures)
  }
  
  if (typeof value !== 'string') {
    return key; // Return key if translation not found
  }
  
  // Simple interpolation
  return value.replace(/\{(\w+)\}/g, (_, name) => params[name] ?? `{${name}}`);
}

export default translations;
